# Generated by Django 3.1.5 on 2024-05-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0002_auto_20240505_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment_details',
            name='status',
        ),
    ]
