# Generated by Django 3.1.5 on 2024-05-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0003_auto_20240505_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_table',
            options={'verbose_name_plural': 'test_table'},
        ),
    ]
