# Generated by Django 3.1.5 on 2024-05-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0004_auto_20240505_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='cart_items',
            options={'verbose_name_plural': 'cart_items'},
        ),
        migrations.AlterModelOptions(
            name='carts',
            options={'verbose_name_plural': 'carts'},
        ),
        migrations.AlterModelOptions(
            name='motor_types',
            options={'verbose_name_plural': 'motor_types'},
        ),
        migrations.AlterModelOptions(
            name='motorbike_attributes',
            options={'verbose_name_plural': 'motorbike_attributes'},
        ),
        migrations.AlterModelOptions(
            name='motorbike_skus',
            options={'verbose_name_plural': 'motorbike_skus'},
        ),
        migrations.AlterModelOptions(
            name='motorbikes',
            options={'verbose_name_plural': 'motorbikes'},
        ),
        migrations.AlterModelOptions(
            name='order_details',
            options={'verbose_name_plural': 'order_details'},
        ),
        migrations.AlterModelOptions(
            name='order_items',
            options={'verbose_name_plural': 'order_items'},
        ),
        migrations.AlterModelOptions(
            name='payment_details',
            options={'verbose_name_plural': 'payment_details'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'users'},
        ),
    ]
