# Generated by Django 3.1.5 on 2024-05-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0005_auto_20240505_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_types',
            name='type_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kiểu xe'),
        ),
    ]
