# Generated by Django 3.1.5 on 2024-05-05 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0006_auto_20240505_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên thương hiệu'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbike_skus', verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Tổng số lượng xe'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.users', verbose_name='Người mua'),
        ),
        migrations.AlterField(
            model_name='motorbike_attributes',
            name='attribute_type',
            field=models.CharField(choices=[('color', 'Color'), ('option', 'Option')], default='color', max_length=10, verbose_name='Kiểu phân loại'),
        ),
        migrations.AlterField(
            model_name='motorbike_attributes',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='motorbike_skus',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='app_test_db.motorbike_attributes', verbose_name='Phiên bản màu'),
        ),
        migrations.AlterField(
            model_name='motorbike_skus',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='app_test_db.motorbike_attributes', verbose_name='Cấu hình'),
        ),
        migrations.AlterField(
            model_name='motorbike_skus',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='motorbike_skus',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2025)], verbose_name='Năm sản xuất'),
        ),
        migrations.AlterField(
            model_name='motorbikes',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.brands', verbose_name='Thương hiệu'),
        ),
        migrations.AlterField(
            model_name='motorbikes',
            name='description',
            field=models.CharField(max_length=2000, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='motorbikes',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motor_types', verbose_name='Kiểu xe'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Tổng số lượng xe'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.users', verbose_name='Người mua'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbike_skus', verbose_name='Phiên bản xe'),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='payment_type',
            field=models.CharField(max_length=20, verbose_name='Kiểu thanh toán'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ và tên đầy đủ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số điện thoại'),
        ),
    ]
