# Generated by Django 3.1.5 on 2024-05-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0010_auto_20240505_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_images',
            name='motorbike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbikes'),
        ),
    ]
