# Generated by Django 3.1.5 on 2024-05-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0011_library_images_motorbike'),
    ]

    operations = [
        migrations.CreateModel(
            name='motorbike_features',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_type', models.CharField(max_length=100, verbose_name='Kiểu tính năng')),
            ],
            options={
                'verbose_name_plural': 'motorbike_features',
            },
        ),
        migrations.AlterField(
            model_name='library_images',
            name='image',
            field=models.ImageField(upload_to='library_images', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='library_images',
            name='motorbike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbikes', verbose_name='Model xe'),
        ),
        migrations.AlterField(
            model_name='motorbike_skus',
            name='motorbike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbikes', verbose_name='Model xe'),
        ),
        migrations.CreateModel(
            name='motorbike_specs',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('mass_ifself', models.FloatField(blank=True, verbose_name='Khối lượng bản thân')),
                ('length', models.IntegerField(blank=True, verbose_name='Dài')),
                ('width', models.IntegerField(blank=True, verbose_name='Rộng')),
                ('height', models.IntegerField(blank=True, verbose_name='Cao')),
                ('wheel_hub_spacing', models.IntegerField(blank=True, verbose_name='Khoảng cách trục bánh xe')),
                ('saddle_height', models.IntegerField(blank=True, verbose_name='Độ cao yên')),
                ('ground_clearance', models.IntegerField(blank=True, verbose_name='Khoảng sáng gầm xe')),
                ('fuel_tank_capacity', models.IntegerField(blank=True, verbose_name='Dung tích bình xăng')),
                ('front_layer_sizes', models.CharField(blank=True, max_length=100, verbose_name='Kích cỡ lốp trước')),
                ('rear_layer_sizes', models.CharField(blank=True, max_length=100, verbose_name='Kích cỡ lốp sau')),
                ('front_fork', models.CharField(blank=True, max_length=100, verbose_name='Phuộc trước')),
                ('rear_fork', models.CharField(blank=True, max_length=100, verbose_name='Phuộc sau')),
                ('engine_type', models.CharField(blank=True, max_length=100, verbose_name='Loại động cơ')),
                ('max_power', models.CharField(blank=True, max_length=100, verbose_name='Công suất tối đa')),
                ('machine_viscosity_capacity', models.CharField(blank=True, max_length=100, verbose_name='Dung tích nhớt máy')),
                ('fuel_consumption', models.CharField(blank=True, max_length=100, verbose_name='Mức tiêu thụ nhiên liệu')),
                ('gearbox', models.CharField(blank=True, max_length=100, verbose_name='Hộp số')),
                ('drive_type', models.CharField(blank=True, max_length=100, verbose_name='Loại truyền động')),
                ('start_up_system', models.CharField(blank=True, max_length=100, verbose_name='Hệ thống khởi động')),
                ('max_moment', models.CharField(blank=True, max_length=100, verbose_name='Moment cực đại')),
                ('cylinder_capacity', models.FloatField(blank=True, verbose_name='Dung tích xi lanh')),
                ('diameter_plunger_stroke', models.CharField(blank=True, max_length=100, verbose_name='Đường kính x Hành trình pít tông')),
                ('compression_ratio', models.CharField(blank=True, max_length=100, verbose_name='Tỷ số nén')),
                ('motorbike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbikes', verbose_name='Model xe')),
            ],
            options={
                'verbose_name_plural': 'motorbike_specs',
            },
        ),
        migrations.CreateModel(
            name='motorbike_feature_images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='feature_images', verbose_name='Hình ảnh')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbike_features', verbose_name='Kiểu tính năng')),
                ('motorbike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbikes', verbose_name='Model xe')),
            ],
            options={
                'verbose_name_plural': 'motorbike_feature_images',
            },
        ),
    ]
