# Generated by Django 3.1.5 on 2024-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0013_auto_20240506_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbike_feature_images',
            name='description',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
