# Generated by Django 3.1.5 on 2024-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0017_auto_20240506_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbike_attributes',
            name='color_1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='motorbike_attributes',
            name='color_2',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
