# Generated by Django 3.1.5 on 2024-05-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0018_auto_20240506_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_table_test',
        ),
        migrations.DeleteModel(
            name='test_table',
        ),
        migrations.AlterModelTable(
            name='brands',
            table='brands',
        ),
        migrations.AlterModelTable(
            name='motor_types',
            table='motor_types',
        ),
    ]
