# Generated by Django 3.1.5 on 2024-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0020_auto_20240507_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='brand_images'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='max_moment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mô-men xoắn cực đại'),
        ),
    ]
