# Generated by Django 3.1.5 on 2024-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0022_auto_20240507_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbikes',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='banner_images'),
        ),
    ]
