# Generated by Django 3.1.5 on 2024-05-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0024_auto_20240507_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike_skus',
            name='color',
            field=models.ForeignKey(limit_choices_to={'attribute_type': 'color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='app_test_db.motorbike_attributes', verbose_name='Phiên bản màu'),
        ),
    ]
