# Generated by Django 3.1.5 on 2024-05-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0025_auto_20240508_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike_skus',
            name='option',
            field=models.ForeignKey(limit_choices_to={'attribute_type': 'option'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='app_test_db.motorbike_attributes', verbose_name='Cấu hình'),
        ),
    ]
