# Generated by Django 3.1.5 on 2024-05-08 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0026_auto_20240508_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike_skus',
            name='year',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2025)], verbose_name='Năm sản xuất'),
        ),
    ]
