# Generated by Django 3.1.5 on 2024-04-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_auto_20240413_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Address Entries'},
        ),
    ]
