# Generated by Django 3.1.5 on 2024-04-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_auto_20240413_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
